name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU (optional, for cross‑platform builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2                # ← official action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    # ← must be a Docker Hub PAT with write scope

    - name: Build and push Docker image
      uses: docker/build-push-action@v5            # ← official build‑and‑push action
      with:
        context: .
        push: true
        tags: 8910792003/gh-actions-next:latest
