name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t 8910792003/gh-actions-next
    - run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u 8910792003 --password-stdin
    - run: docker push 8910792003/gh-actions-next:latest
